#!/bin/bash

pushd $1 > /dev/null
for a in [0-9]*.$2; do
    mv $a `printf %04d.%s ${a%.*} ${a##*.}`
done

echo Converting...

convert *.$2 *.pdf && convert *.pdf -adjoin $3

echo Done

popd > /dev/null